// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tsm.proto

#include "tsm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace tsm {
class UserNameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UserName>
      _instance;
} _UserName_default_instance_;
class UserIdDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UserId>
      _instance;
} _UserId_default_instance_;
class FollowCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FollowCommand>
      _instance;
} _FollowCommand_default_instance_;
class UnfollowCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UnfollowCommand>
      _instance;
} _UnfollowCommand_default_instance_;
class GeneralStatusDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GeneralStatus>
      _instance;
} _GeneralStatus_default_instance_;
class ListReplyDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListReply>
      _instance;
} _ListReply_default_instance_;
class ClientPostDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClientPost>
      _instance;
} _ClientPost_default_instance_;
class ServerPostDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ServerPost>
      _instance;
} _ServerPost_default_instance_;
}  // namespace tsm
namespace protobuf_tsm_2eproto {
void InitDefaultsUserNameImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_UserName_default_instance_;
    new (ptr) ::tsm::UserName();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::UserName::InitAsDefaultInstance();
}

void InitDefaultsUserName() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsUserNameImpl);
}

void InitDefaultsUserIdImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_UserId_default_instance_;
    new (ptr) ::tsm::UserId();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::UserId::InitAsDefaultInstance();
}

void InitDefaultsUserId() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsUserIdImpl);
}

void InitDefaultsFollowCommandImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_FollowCommand_default_instance_;
    new (ptr) ::tsm::FollowCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::FollowCommand::InitAsDefaultInstance();
}

void InitDefaultsFollowCommand() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFollowCommandImpl);
}

void InitDefaultsUnfollowCommandImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_UnfollowCommand_default_instance_;
    new (ptr) ::tsm::UnfollowCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::UnfollowCommand::InitAsDefaultInstance();
}

void InitDefaultsUnfollowCommand() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsUnfollowCommandImpl);
}

void InitDefaultsGeneralStatusImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_GeneralStatus_default_instance_;
    new (ptr) ::tsm::GeneralStatus();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::GeneralStatus::InitAsDefaultInstance();
}

void InitDefaultsGeneralStatus() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsGeneralStatusImpl);
}

void InitDefaultsListReplyImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_ListReply_default_instance_;
    new (ptr) ::tsm::ListReply();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::ListReply::InitAsDefaultInstance();
}

void InitDefaultsListReply() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsListReplyImpl);
}

void InitDefaultsClientPostImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_ClientPost_default_instance_;
    new (ptr) ::tsm::ClientPost();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::ClientPost::InitAsDefaultInstance();
}

void InitDefaultsClientPost() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsClientPostImpl);
}

void InitDefaultsServerPostImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tsm::_ServerPost_default_instance_;
    new (ptr) ::tsm::ServerPost();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tsm::ServerPost::InitAsDefaultInstance();
}

void InitDefaultsServerPost() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsServerPostImpl);
}

::google::protobuf::Metadata file_level_metadata[8];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::UserName, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::UserName, name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::UserId, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::UserId, id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::FollowCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::FollowCommand, sender_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::FollowCommand, nametofollow_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::UnfollowCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::UnfollowCommand, sender_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::UnfollowCommand, nametounfollow_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::GeneralStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::GeneralStatus, status_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ListReply, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ListReply, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ListReply, users_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ListReply, followings_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ClientPost, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ClientPost, sender_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ClientPost, content_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ServerPost, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ServerPost, content_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ServerPost, time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tsm::ServerPost, sendername_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tsm::UserName)},
  { 6, -1, sizeof(::tsm::UserId)},
  { 12, -1, sizeof(::tsm::FollowCommand)},
  { 19, -1, sizeof(::tsm::UnfollowCommand)},
  { 26, -1, sizeof(::tsm::GeneralStatus)},
  { 32, -1, sizeof(::tsm::ListReply)},
  { 40, -1, sizeof(::tsm::ClientPost)},
  { 47, -1, sizeof(::tsm::ServerPost)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_UserName_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_UserId_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_FollowCommand_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_UnfollowCommand_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_GeneralStatus_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_ListReply_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_ClientPost_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::tsm::_ServerPost_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tsm.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 8);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\ttsm.proto\022\003tsm\"\030\n\010UserName\022\014\n\004name\030\001 \001"
      "(\t\"\024\n\006UserId\022\n\n\002id\030\001 \001(\003\"5\n\rFollowComman"
      "d\022\016\n\006sender\030\001 \001(\003\022\024\n\014nameToFollow\030\002 \001(\t\""
      "9\n\017UnfollowCommand\022\016\n\006sender\030\001 \001(\003\022\026\n\016na"
      "meToUnfollow\030\002 \001(\t\"-\n\rGeneralStatus\022\034\n\006s"
      "tatus\030\001 \001(\0162\014.tsm.GStatus\"L\n\tListReply\022\034"
      "\n\006status\030\001 \001(\0162\014.tsm.GStatus\022\r\n\005users\030\002 "
      "\003(\t\022\022\n\nfollowings\030\003 \003(\t\"-\n\nClientPost\022\016\n"
      "\006sender\030\001 \001(\003\022\017\n\007content\030\002 \001(\t\"\?\n\nServer"
      "Post\022\017\n\007content\030\001 \001(\t\022\014\n\004time\030\002 \001(\005\022\022\n\ns"
      "enderName\030\003 \001(\t*\222\001\n\007GStatus\022\013\n\007SUCCESS\020\000"
      "\022\032\n\026FAILURE_ALREADY_EXISTS\020\001\022\026\n\022FAILURE_"
      "NOT_EXISTS\020\002\022\034\n\030FAILURE_INVALID_USERNAME"
      "\020\003\022\023\n\017FAILURE_INVALID\020\004\022\023\n\017FAILURE_UNKNO"
      "WN\020\0052\211\002\n\017TinySocialMedia\022*\n\njoinServer\022\r"
      ".tsm.UserName\032\013.tsm.UserId\"\000\0222\n\006follow\022\022"
      ".tsm.FollowCommand\032\022.tsm.GeneralStatus\"\000"
      "\0226\n\010unfollow\022\024.tsm.UnfollowCommand\032\022.tsm"
      ".GeneralStatus\"\000\022*\n\tlistUsers\022\013.tsm.User"
      "Id\032\016.tsm.ListReply\"\000\0222\n\010timeline\022\017.tsm.C"
      "lientPost\032\017.tsm.ServerPost\"\000(\0010\001B(\n\024io.g"
      "rpc.examples.tsmB\010TsmProtoP\001\242\002\003TSMb\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 882);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tsm.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_tsm_2eproto
namespace tsm {
const ::google::protobuf::EnumDescriptor* GStatus_descriptor() {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tsm_2eproto::file_level_enum_descriptors[0];
}
bool GStatus_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void UserName::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserName::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserName::UserName()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsUserName();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.UserName)
}
UserName::UserName(const UserName& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:tsm.UserName)
}

void UserName::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

UserName::~UserName() {
  // @@protoc_insertion_point(destructor:tsm.UserName)
  SharedDtor();
}

void UserName::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UserName::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserName::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UserName& UserName::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsUserName();
  return *internal_default_instance();
}

UserName* UserName::New(::google::protobuf::Arena* arena) const {
  UserName* n = new UserName;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UserName::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.UserName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool UserName::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.UserName)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.UserName.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.UserName)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.UserName)
  return false;
#undef DO_
}

void UserName::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.UserName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.UserName.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.UserName)
}

::google::protobuf::uint8* UserName::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.UserName)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.UserName.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.UserName)
  return target;
}

size_t UserName::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.UserName)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UserName::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.UserName)
  GOOGLE_DCHECK_NE(&from, this);
  const UserName* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UserName>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.UserName)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.UserName)
    MergeFrom(*source);
  }
}

void UserName::MergeFrom(const UserName& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.UserName)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void UserName::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.UserName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserName::CopyFrom(const UserName& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.UserName)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserName::IsInitialized() const {
  return true;
}

void UserName::Swap(UserName* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserName::InternalSwap(UserName* other) {
  using std::swap;
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UserName::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UserId::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UserId::kIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UserId::UserId()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsUserId();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.UserId)
}
UserId::UserId(const UserId& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:tsm.UserId)
}

void UserId::SharedCtor() {
  id_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

UserId::~UserId() {
  // @@protoc_insertion_point(destructor:tsm.UserId)
  SharedDtor();
}

void UserId::SharedDtor() {
}

void UserId::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UserId::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UserId& UserId::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsUserId();
  return *internal_default_instance();
}

UserId* UserId::New(::google::protobuf::Arena* arena) const {
  UserId* n = new UserId;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UserId::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.UserId)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool UserId::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.UserId)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.UserId)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.UserId)
  return false;
#undef DO_
}

void UserId::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.UserId)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.UserId)
}

::google::protobuf::uint8* UserId::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.UserId)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.UserId)
  return target;
}

size_t UserId::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.UserId)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UserId::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.UserId)
  GOOGLE_DCHECK_NE(&from, this);
  const UserId* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UserId>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.UserId)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.UserId)
    MergeFrom(*source);
  }
}

void UserId::MergeFrom(const UserId& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.UserId)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    set_id(from.id());
  }
}

void UserId::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.UserId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UserId::CopyFrom(const UserId& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.UserId)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UserId::IsInitialized() const {
  return true;
}

void UserId::Swap(UserId* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UserId::InternalSwap(UserId* other) {
  using std::swap;
  swap(id_, other->id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UserId::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void FollowCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FollowCommand::kSenderFieldNumber;
const int FollowCommand::kNameToFollowFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FollowCommand::FollowCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsFollowCommand();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.FollowCommand)
}
FollowCommand::FollowCommand(const FollowCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  nametofollow_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nametofollow().size() > 0) {
    nametofollow_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nametofollow_);
  }
  sender_ = from.sender_;
  // @@protoc_insertion_point(copy_constructor:tsm.FollowCommand)
}

void FollowCommand::SharedCtor() {
  nametofollow_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

FollowCommand::~FollowCommand() {
  // @@protoc_insertion_point(destructor:tsm.FollowCommand)
  SharedDtor();
}

void FollowCommand::SharedDtor() {
  nametofollow_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FollowCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FollowCommand::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FollowCommand& FollowCommand::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsFollowCommand();
  return *internal_default_instance();
}

FollowCommand* FollowCommand::New(::google::protobuf::Arena* arena) const {
  FollowCommand* n = new FollowCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FollowCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.FollowCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nametofollow_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool FollowCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.FollowCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 sender = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sender_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string nameToFollow = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nametofollow()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nametofollow().data(), static_cast<int>(this->nametofollow().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.FollowCommand.nameToFollow"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.FollowCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.FollowCommand)
  return false;
#undef DO_
}

void FollowCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.FollowCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->sender(), output);
  }

  // string nameToFollow = 2;
  if (this->nametofollow().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nametofollow().data(), static_cast<int>(this->nametofollow().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.FollowCommand.nameToFollow");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nametofollow(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.FollowCommand)
}

::google::protobuf::uint8* FollowCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.FollowCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->sender(), target);
  }

  // string nameToFollow = 2;
  if (this->nametofollow().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nametofollow().data(), static_cast<int>(this->nametofollow().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.FollowCommand.nameToFollow");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nametofollow(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.FollowCommand)
  return target;
}

size_t FollowCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.FollowCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string nameToFollow = 2;
  if (this->nametofollow().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nametofollow());
  }

  // int64 sender = 1;
  if (this->sender() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->sender());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FollowCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.FollowCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const FollowCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FollowCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.FollowCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.FollowCommand)
    MergeFrom(*source);
  }
}

void FollowCommand::MergeFrom(const FollowCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.FollowCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.nametofollow().size() > 0) {

    nametofollow_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nametofollow_);
  }
  if (from.sender() != 0) {
    set_sender(from.sender());
  }
}

void FollowCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.FollowCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FollowCommand::CopyFrom(const FollowCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.FollowCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FollowCommand::IsInitialized() const {
  return true;
}

void FollowCommand::Swap(FollowCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FollowCommand::InternalSwap(FollowCommand* other) {
  using std::swap;
  nametofollow_.Swap(&other->nametofollow_);
  swap(sender_, other->sender_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FollowCommand::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UnfollowCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UnfollowCommand::kSenderFieldNumber;
const int UnfollowCommand::kNameToUnfollowFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UnfollowCommand::UnfollowCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsUnfollowCommand();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.UnfollowCommand)
}
UnfollowCommand::UnfollowCommand(const UnfollowCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  nametounfollow_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nametounfollow().size() > 0) {
    nametounfollow_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nametounfollow_);
  }
  sender_ = from.sender_;
  // @@protoc_insertion_point(copy_constructor:tsm.UnfollowCommand)
}

void UnfollowCommand::SharedCtor() {
  nametounfollow_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

UnfollowCommand::~UnfollowCommand() {
  // @@protoc_insertion_point(destructor:tsm.UnfollowCommand)
  SharedDtor();
}

void UnfollowCommand::SharedDtor() {
  nametounfollow_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void UnfollowCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* UnfollowCommand::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UnfollowCommand& UnfollowCommand::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsUnfollowCommand();
  return *internal_default_instance();
}

UnfollowCommand* UnfollowCommand::New(::google::protobuf::Arena* arena) const {
  UnfollowCommand* n = new UnfollowCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void UnfollowCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.UnfollowCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nametounfollow_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool UnfollowCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.UnfollowCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 sender = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sender_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string nameToUnfollow = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nametounfollow()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nametounfollow().data(), static_cast<int>(this->nametounfollow().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.UnfollowCommand.nameToUnfollow"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.UnfollowCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.UnfollowCommand)
  return false;
#undef DO_
}

void UnfollowCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.UnfollowCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->sender(), output);
  }

  // string nameToUnfollow = 2;
  if (this->nametounfollow().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nametounfollow().data(), static_cast<int>(this->nametounfollow().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.UnfollowCommand.nameToUnfollow");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->nametounfollow(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.UnfollowCommand)
}

::google::protobuf::uint8* UnfollowCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.UnfollowCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->sender(), target);
  }

  // string nameToUnfollow = 2;
  if (this->nametounfollow().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nametounfollow().data(), static_cast<int>(this->nametounfollow().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.UnfollowCommand.nameToUnfollow");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->nametounfollow(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.UnfollowCommand)
  return target;
}

size_t UnfollowCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.UnfollowCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string nameToUnfollow = 2;
  if (this->nametounfollow().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nametounfollow());
  }

  // int64 sender = 1;
  if (this->sender() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->sender());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void UnfollowCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.UnfollowCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const UnfollowCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UnfollowCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.UnfollowCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.UnfollowCommand)
    MergeFrom(*source);
  }
}

void UnfollowCommand::MergeFrom(const UnfollowCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.UnfollowCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.nametounfollow().size() > 0) {

    nametounfollow_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nametounfollow_);
  }
  if (from.sender() != 0) {
    set_sender(from.sender());
  }
}

void UnfollowCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.UnfollowCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnfollowCommand::CopyFrom(const UnfollowCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.UnfollowCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnfollowCommand::IsInitialized() const {
  return true;
}

void UnfollowCommand::Swap(UnfollowCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UnfollowCommand::InternalSwap(UnfollowCommand* other) {
  using std::swap;
  nametounfollow_.Swap(&other->nametounfollow_);
  swap(sender_, other->sender_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata UnfollowCommand::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GeneralStatus::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GeneralStatus::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GeneralStatus::GeneralStatus()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsGeneralStatus();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.GeneralStatus)
}
GeneralStatus::GeneralStatus(const GeneralStatus& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:tsm.GeneralStatus)
}

void GeneralStatus::SharedCtor() {
  status_ = 0;
  _cached_size_ = 0;
}

GeneralStatus::~GeneralStatus() {
  // @@protoc_insertion_point(destructor:tsm.GeneralStatus)
  SharedDtor();
}

void GeneralStatus::SharedDtor() {
}

void GeneralStatus::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GeneralStatus::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GeneralStatus& GeneralStatus::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsGeneralStatus();
  return *internal_default_instance();
}

GeneralStatus* GeneralStatus::New(::google::protobuf::Arena* arena) const {
  GeneralStatus* n = new GeneralStatus;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GeneralStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.GeneralStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_ = 0;
  _internal_metadata_.Clear();
}

bool GeneralStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.GeneralStatus)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tsm.GStatus status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_status(static_cast< ::tsm::GStatus >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.GeneralStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.GeneralStatus)
  return false;
#undef DO_
}

void GeneralStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.GeneralStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tsm.GStatus status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->status(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.GeneralStatus)
}

::google::protobuf::uint8* GeneralStatus::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.GeneralStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tsm.GStatus status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->status(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.GeneralStatus)
  return target;
}

size_t GeneralStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.GeneralStatus)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .tsm.GStatus status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GeneralStatus::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.GeneralStatus)
  GOOGLE_DCHECK_NE(&from, this);
  const GeneralStatus* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GeneralStatus>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.GeneralStatus)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.GeneralStatus)
    MergeFrom(*source);
  }
}

void GeneralStatus::MergeFrom(const GeneralStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.GeneralStatus)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status() != 0) {
    set_status(from.status());
  }
}

void GeneralStatus::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.GeneralStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GeneralStatus::CopyFrom(const GeneralStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.GeneralStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GeneralStatus::IsInitialized() const {
  return true;
}

void GeneralStatus::Swap(GeneralStatus* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GeneralStatus::InternalSwap(GeneralStatus* other) {
  using std::swap;
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GeneralStatus::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ListReply::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListReply::kStatusFieldNumber;
const int ListReply::kUsersFieldNumber;
const int ListReply::kFollowingsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListReply::ListReply()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsListReply();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.ListReply)
}
ListReply::ListReply(const ListReply& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      users_(from.users_),
      followings_(from.followings_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_ = from.status_;
  // @@protoc_insertion_point(copy_constructor:tsm.ListReply)
}

void ListReply::SharedCtor() {
  status_ = 0;
  _cached_size_ = 0;
}

ListReply::~ListReply() {
  // @@protoc_insertion_point(destructor:tsm.ListReply)
  SharedDtor();
}

void ListReply::SharedDtor() {
}

void ListReply::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ListReply::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ListReply& ListReply::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsListReply();
  return *internal_default_instance();
}

ListReply* ListReply::New(::google::protobuf::Arena* arena) const {
  ListReply* n = new ListReply;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ListReply::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.ListReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  users_.Clear();
  followings_.Clear();
  status_ = 0;
  _internal_metadata_.Clear();
}

bool ListReply::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.ListReply)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tsm.GStatus status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_status(static_cast< ::tsm::GStatus >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string users = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_users()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->users(this->users_size() - 1).data(),
            static_cast<int>(this->users(this->users_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.ListReply.users"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string followings = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_followings()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->followings(this->followings_size() - 1).data(),
            static_cast<int>(this->followings(this->followings_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.ListReply.followings"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.ListReply)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.ListReply)
  return false;
#undef DO_
}

void ListReply::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.ListReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tsm.GStatus status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->status(), output);
  }

  // repeated string users = 2;
  for (int i = 0, n = this->users_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->users(i).data(), static_cast<int>(this->users(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ListReply.users");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->users(i), output);
  }

  // repeated string followings = 3;
  for (int i = 0, n = this->followings_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->followings(i).data(), static_cast<int>(this->followings(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ListReply.followings");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->followings(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.ListReply)
}

::google::protobuf::uint8* ListReply::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.ListReply)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tsm.GStatus status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->status(), target);
  }

  // repeated string users = 2;
  for (int i = 0, n = this->users_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->users(i).data(), static_cast<int>(this->users(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ListReply.users");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->users(i), target);
  }

  // repeated string followings = 3;
  for (int i = 0, n = this->followings_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->followings(i).data(), static_cast<int>(this->followings(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ListReply.followings");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->followings(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.ListReply)
  return target;
}

size_t ListReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.ListReply)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string users = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->users_size());
  for (int i = 0, n = this->users_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->users(i));
  }

  // repeated string followings = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->followings_size());
  for (int i = 0, n = this->followings_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->followings(i));
  }

  // .tsm.GStatus status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ListReply::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.ListReply)
  GOOGLE_DCHECK_NE(&from, this);
  const ListReply* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ListReply>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.ListReply)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.ListReply)
    MergeFrom(*source);
  }
}

void ListReply::MergeFrom(const ListReply& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.ListReply)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  users_.MergeFrom(from.users_);
  followings_.MergeFrom(from.followings_);
  if (from.status() != 0) {
    set_status(from.status());
  }
}

void ListReply::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.ListReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListReply::CopyFrom(const ListReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.ListReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListReply::IsInitialized() const {
  return true;
}

void ListReply::Swap(ListReply* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ListReply::InternalSwap(ListReply* other) {
  using std::swap;
  users_.InternalSwap(&other->users_);
  followings_.InternalSwap(&other->followings_);
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ListReply::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ClientPost::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClientPost::kSenderFieldNumber;
const int ClientPost::kContentFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClientPost::ClientPost()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsClientPost();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.ClientPost)
}
ClientPost::ClientPost(const ClientPost& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  sender_ = from.sender_;
  // @@protoc_insertion_point(copy_constructor:tsm.ClientPost)
}

void ClientPost::SharedCtor() {
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_ = GOOGLE_LONGLONG(0);
  _cached_size_ = 0;
}

ClientPost::~ClientPost() {
  // @@protoc_insertion_point(destructor:tsm.ClientPost)
  SharedDtor();
}

void ClientPost::SharedDtor() {
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ClientPost::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ClientPost::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClientPost& ClientPost::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsClientPost();
  return *internal_default_instance();
}

ClientPost* ClientPost::New(::google::protobuf::Arena* arena) const {
  ClientPost* n = new ClientPost;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ClientPost::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.ClientPost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool ClientPost::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.ClientPost)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 sender = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sender_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string content = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), static_cast<int>(this->content().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.ClientPost.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.ClientPost)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.ClientPost)
  return false;
#undef DO_
}

void ClientPost::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.ClientPost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->sender(), output);
  }

  // string content = 2;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ClientPost.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->content(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.ClientPost)
}

::google::protobuf::uint8* ClientPost::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.ClientPost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sender = 1;
  if (this->sender() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->sender(), target);
  }

  // string content = 2;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ClientPost.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->content(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.ClientPost)
  return target;
}

size_t ClientPost::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.ClientPost)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string content = 2;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  // int64 sender = 1;
  if (this->sender() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->sender());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ClientPost::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.ClientPost)
  GOOGLE_DCHECK_NE(&from, this);
  const ClientPost* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClientPost>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.ClientPost)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.ClientPost)
    MergeFrom(*source);
  }
}

void ClientPost::MergeFrom(const ClientPost& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.ClientPost)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  if (from.sender() != 0) {
    set_sender(from.sender());
  }
}

void ClientPost::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.ClientPost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClientPost::CopyFrom(const ClientPost& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.ClientPost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClientPost::IsInitialized() const {
  return true;
}

void ClientPost::Swap(ClientPost* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClientPost::InternalSwap(ClientPost* other) {
  using std::swap;
  content_.Swap(&other->content_);
  swap(sender_, other->sender_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ClientPost::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ServerPost::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ServerPost::kContentFieldNumber;
const int ServerPost::kTimeFieldNumber;
const int ServerPost::kSenderNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ServerPost::ServerPost()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_tsm_2eproto::InitDefaultsServerPost();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tsm.ServerPost)
}
ServerPost::ServerPost(const ServerPost& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  sendername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.sendername().size() > 0) {
    sendername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sendername_);
  }
  time_ = from.time_;
  // @@protoc_insertion_point(copy_constructor:tsm.ServerPost)
}

void ServerPost::SharedCtor() {
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sendername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_ = 0;
  _cached_size_ = 0;
}

ServerPost::~ServerPost() {
  // @@protoc_insertion_point(destructor:tsm.ServerPost)
  SharedDtor();
}

void ServerPost::SharedDtor() {
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sendername_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ServerPost::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ServerPost::descriptor() {
  ::protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ServerPost& ServerPost::default_instance() {
  ::protobuf_tsm_2eproto::InitDefaultsServerPost();
  return *internal_default_instance();
}

ServerPost* ServerPost::New(::google::protobuf::Arena* arena) const {
  ServerPost* n = new ServerPost;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ServerPost::Clear() {
// @@protoc_insertion_point(message_clear_start:tsm.ServerPost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sendername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  time_ = 0;
  _internal_metadata_.Clear();
}

bool ServerPost::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tsm.ServerPost)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string content = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), static_cast<int>(this->content().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.ServerPost.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 time = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &time_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string senderName = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sendername()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->sendername().data(), static_cast<int>(this->sendername().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tsm.ServerPost.senderName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tsm.ServerPost)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tsm.ServerPost)
  return false;
#undef DO_
}

void ServerPost::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tsm.ServerPost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ServerPost.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content(), output);
  }

  // int32 time = 2;
  if (this->time() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->time(), output);
  }

  // string senderName = 3;
  if (this->sendername().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sendername().data(), static_cast<int>(this->sendername().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ServerPost.senderName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->sendername(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tsm.ServerPost)
}

::google::protobuf::uint8* ServerPost::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tsm.ServerPost)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ServerPost.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->content(), target);
  }

  // int32 time = 2;
  if (this->time() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->time(), target);
  }

  // string senderName = 3;
  if (this->sendername().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->sendername().data(), static_cast<int>(this->sendername().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tsm.ServerPost.senderName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->sendername(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tsm.ServerPost)
  return target;
}

size_t ServerPost::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tsm.ServerPost)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string content = 1;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  // string senderName = 3;
  if (this->sendername().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->sendername());
  }

  // int32 time = 2;
  if (this->time() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->time());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ServerPost::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tsm.ServerPost)
  GOOGLE_DCHECK_NE(&from, this);
  const ServerPost* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ServerPost>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tsm.ServerPost)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tsm.ServerPost)
    MergeFrom(*source);
  }
}

void ServerPost::MergeFrom(const ServerPost& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tsm.ServerPost)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  if (from.sendername().size() > 0) {

    sendername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sendername_);
  }
  if (from.time() != 0) {
    set_time(from.time());
  }
}

void ServerPost::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tsm.ServerPost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ServerPost::CopyFrom(const ServerPost& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tsm.ServerPost)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ServerPost::IsInitialized() const {
  return true;
}

void ServerPost::Swap(ServerPost* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ServerPost::InternalSwap(ServerPost* other) {
  using std::swap;
  content_.Swap(&other->content_);
  sendername_.Swap(&other->sendername_);
  swap(time_, other->time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ServerPost::GetMetadata() const {
  protobuf_tsm_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_tsm_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tsm

// @@protoc_insertion_point(global_scope)
